### ISSUE TITLE
how to increase memory

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/WhiteRabbit#103]
What syntax can be used with the jar.

e.g. , java  rabit.jar -Xmemory16Gb

to increase the memory.

Error occured for memory and also for writing the file while disk had 0.4GB of free space. why?

```

*** Generic error information ***
Message: java.sql.SQLException: Error writing file '/var/lib/mysqltmp/MY90E7WY' (Errcode: 28 - No space left on device)
Time: Jan 7, 2016 10:44:30 AM
Processor type: amd64
Available processors: 8
Maximum available memory: 3,806,855,168 bytes
Used memory: 191,616,688 bytes
Java version: 1.8.0_66
Java vendor: Oracle Corporation
OS architecture: amd64
OS name: Windows 7
OS version: 6.1
OS patch level: Service Pack 1

*** Stack trace ***
org.ohdsi.databases.RichConnection$DBRowIterator.<init>(RichConnection.java:421)
org.ohdsi.databases.RichConnection$QueryResult.iterator(RichConnection.java:204)
org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:255)
org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:140)
org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:126)
org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:861)

*** Console ***
Dec 31, 2015 2:51:20 PM Scanning table ADMISSIONS
Dec 31, 2015 2:51:22 PM Scanning table CALLOUT
Dec 31, 2015 2:51:23 PM Scanning table CAREGIVERS
Dec 31, 2015 2:51:23 PM Scanning table CHARTEVENTS
Exception in thread "Thread-3" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2149)
    at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1956)
    at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3308)
    at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:463)
    at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3032)
    at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2280)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
    at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
    at org.ohdsi.databases.RichConnection$DBRowIterator.<init>(RichConnection.java:414)
    at org.ohdsi.databases.RichConnection$QueryResult.iterator(RichConnection.java:204)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:255)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:140)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:126)
    at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:861)
Jan 5, 2016 4:11:50 PM  Scanning table ADMISSIONS
Jan 5, 2016 4:11:52 PM  Scanning table CALLOUT
Jan 5, 2016 4:11:54 PM  Scanning table CAREGIVERS
Jan 5, 2016 4:11:54 PM  Scanning table CHARTEVENTS
Exception in thread "Thread-4" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2149)
    at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1956)
    at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3308)
    at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:463)
    at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3032)
    at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2280)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2546)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2504)
    at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
    at org.ohdsi.databases.RichConnection$DBRowIterator.<init>(RichConnection.java:414)
    at org.ohdsi.databases.RichConnection$QueryResult.iterator(RichConnection.java:204)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:255)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:140)
    at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:126)
    at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:861)
Jan 7, 2016 9:17:57 AM  Scanning table ADMISSIONS
Jan 7, 2016 9:17:58 AM  Scanning table CALLOUT
Jan 7, 2016 9:18:00 AM  Scanning table CAREGIVERS
Jan 7, 2016 9:18:00 AM  Scanning table CHARTEVENTS
SELECT * FROM CHARTEVENTS ORDER BY RAND() LIMIT 100000
Error writing file '/var/lib/mysqltmp/MY90E7WY' (Errcode: 28 - No space left on device)
Error: java.sql.SQLException: Error writing file '/var/lib/mysqltmp/MY90E7WY' (Errcode: 28 - No space left on device)


*** Working folder contents ***
Directory of c:\net\WhiteRabbit_v0.5.6

WhiteRabbit.jar                                                          306,695                   08-11-2015 07:54:11
RabbitInAHat.jar                                                         598,677                   08-11-2015 07:54:11
WhiteRabbit_lib                                                            4,096      <DIR>        08-11-2015 07:54:12
Copy (1) ScanReport.xlsx                                                   9,131                   30-12-2015 03:19:41
~$Copy (1) ScanReport.xlsx                                                   165                   30-12-2015 03:19:54
Copy (2) ScanReport.xlsx                                               1,624,989                   30-12-2015 03:21:27
Copy (3) ScanReport.xlsx                                                   4,423                   30-12-2015 03:22:34
~$Copy (3) ScanReport.xlsx                                                   165                   30-12-2015 03:22:41
Copy (4) ScanReport.xlsx                                                   4,466                   30-12-2015 03:22:57
~$Copy (4) ScanReport.xlsx                                                   165                   30-12-2015 03:23:02
Copy (5) ScanReport.xlsx                                                  30,106                   30-12-2015 03:27:37
Copy (6) ScanReport.xlsx                                                  30,106                   30-12-2015 03:27:37
ScanReport.xlsx                                                           30,106                   30-12-2015 03:27:37
~$Copy (5) ScanReport.xlsx                                                   165                   30-12-2015 03:27:48
Copy (1) Error.txt                                                         9,375                   30-12-2015 04:50:18
Error.txt                                                                  9,375                   30-12-2015 04:50:18
~$Copy (6) ScanReport.xlsx                                                   165                   31-12-2015 11:09:49
Error1.txt                                                                     0                   07-01-2016 10:44:30

Available disc space: 591,066,869,760 bytes
```

**Comment by schuemie** [comment]
Hi Vojtech. 

Several things appear to be going on. First of all, WhiteRabbit seems to run out of memory. You can try this to fix that:
```
java -Xmx16g -jar WhiteRabbit.jar
```

Second, the failure-to-write error is thrown by MySQL, not by WhiteRabbit. Perhaps it can't deal with selecting random rows from a large table? 

In general, PostgreSQL might be a better option than MySQL.
