### ISSUE TITLE
White Rabbit Support For SDO_Geometry Data Types

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/WhiteRabbit#142]
The table scan fails because we have one column that is sdo_geometry.  However, this table contains the source data for the person table so it is needed.

Exception in thread "Thread-5" java.lang.NoClassDefFoundError: oracle/xdb/XMLType
	at oracle.jdbc.driver.NamedTypeAccessor.getString(NamedTypeAccessor.java:355)
	at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:327)
	at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:882)
	at org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:499)
	at org.ohdsi.databases.RichConnection$DBRowIterator.next(RichConnection.java:436)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabaseTable(SourceDataScan.java:261)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.processDatabase(SourceDataScan.java:144)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:130)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:963)

Since this is only one column, will WhiteRabbit have the ability to scan select columns (if we don't need to scan all the columns in the table) in a future release?

**Comment by schuemie** [comment]
We actually just added a [try-catch block](https://github.com/OHDSI/WhiteRabbit/blob/master/src/org/ohdsi/databases/RichConnection.java#L498) so exceptions when converting a field to string would simply result in an empty string. 

It seems Oracle didn't write its JDBC driver very well, actually causing an error (instead of an exception). I could also catch errors, but that is considered bad practice. What do you think?

The ability to exclude columns is on the to-do list, but it may take a while before it is implemented.
