### ISSUE TITLE
Markdown export issues

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WhiteRabbit#222]
Three issues when exporting to markdown:

- [ ] no index.md file created, following error is shown:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.ohdsi.rabbitInAHat.ETLMarkupDocumentGenerator$MarkdownDocument.addTable(ETLMarkupDocumentGenerator.java:319)
	at org.ohdsi.rabbitInAHat.ETLMarkupDocumentGenerator.addSourceTablesAppendix(ETLMarkupDocumentGenerator.java:199)
	at org.ohdsi.rabbitInAHat.ETLMarkupDocumentGenerator.generate(ETLMarkupDocumentGenerator.java:83)
	at org.ohdsi.rabbitInAHat.RabbitInAHatMain.doGenerateEtlMdDoc(RabbitInAHatMain.java:653)
```
- [ ] by default file name has .md extension. Should be a folder
- [ ] images are exported to _files. The underscore gives issues with e.g. Github Pages.

**Comment by MaximMoinat** [comment]
Note that same issue persists for html export (with `.html` extension that is added the folder)

The sql skeleton export works differently, it only needs the folder to be used selected. The given filename is ignored.
