### ISSUE TITLE
WR .ini file setting TABLE_TO_SCAN = * does not work for delimited text files

### ISSUE THREAD

**Issue by alepev** [OHDSI/WhiteRabbit#253]
If I point White Rabbit to an `.ini` file as such: (all database parameters empty, the others set to default)
```
WORKING_FOLDER = ./folder_with_my_tables
DATA_TYPE = Delimited text files
DELIMITER = tab
TABLES_TO_SCAN = table1.tsv,table2.tsv,<tableN>.tsv
```
it reads the tables and produce a scan report as expected.

Now, say I have tenths of tables in the target folder, and I don't want to list them explicitly. I thought I could simply write `TABLES_TO_SCAN = *` (as mentioned in the comment field, see [here](https://github.com/OHDSI/WhiteRabbit/blob/v0.10.1/iniFileExamples/WhiteRabbit.ini)), but that doesn't work:
```
Exception in thread "main" java.lang.NullPointerException
	at org.ohdsi.databases.DBConnector.connect(DBConnector.java:36)
	at org.ohdsi.databases.RichConnection.<init>(RichConnection.java:50)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.launchCommandLine(WhiteRabbitMain.java:204)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.<init>(WhiteRabbitMain.java:126)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain.main(WhiteRabbitMain.java:121)
```
Apparently, this argument can only be used with an `*` when dealing with database tables? Can it be made applicable to delimited files as well?

Tested with WR v0.10.1 and 0.9.0 on MacOS 10.14.6.

**Comment by alepev** [comment]
Incidentally I also noticed the command line documentation still refers to jar files: http://ohdsi.github.io/WhiteRabbit/WhiteRabbit.html#running_from_the_command_line
