### ISSUE TITLE
Bug creating ScanReport in WhiteRabbit v0.10.8

### ISSUE THREAD

**Issue by elisahenke** [OHDSI/WhiteRabbit#375]
Cannot create ScanReport based on csv files in WhiteRabbit v0.10.8.

Steps to reproduce the behavior for WhiteRabbit:
1. Defined working folder
2. Defined delimiter
3. Added csv file to scan
4. Scan tables
5. Error:

_Generating scan report
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org.apache.commons.compress.archivers.ArchiveOutputStream
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.generateReport(SourceDataScan.java:172)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:117)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:1054)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.ArchiveOutputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:788)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1081)
	... 3 more_

We tested this with own csv-files as well as with the test csv-files in the WhiteRabbit repository. The error is displayed for both.

**Comment by janblom** [comment]
One dependency (commons-compress) fell victim to the dependencies update (a version containing vulnerabilities was a transient dependency before). I added a newer version back explicitly. I also verified that all other dependencies compared to version 0.10.7 are unaffected.

@elisahenke could you please test with version 0.10.8a?

**Comment by elisahenke** [comment]
Hi @janblom, the described error is solved with version 0.10.8a. Thank you very much for solving it!

However, the error described in Issue #376 still remains.

**Comment by janblom** [comment]
Solved with release 0.10.8a (included in release 0.10.8).
