### ISSUE TITLE
java.lang.NoClassDefFoundError during report gen

### ISSUE THREAD

**Issue by jtheobaldhp** [OHDSI/WhiteRabbit#378]
**Describe the bug**

This bug occurs with v.10.8
Does not occur when I roll back to v.10.7

**To Reproduce**
Loaded csv files into WR

**Expected behavior**
Expected report to be generated

```
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: org/apache/commons/compress/archivers/zip/ZipFile
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.generateReport(SourceDataScan.java:172)
	at org.ohdsi.whiteRabbit.scan.SourceDataScan.process(SourceDataScan.java:117)
	at org.ohdsi.whiteRabbit.WhiteRabbitMain$ScanThread.run(WhiteRabbitMain.java:1054)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.archivers.zip.ZipFile
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Desktop**
 - Mac Silicon M2

**Comment by janblom** [comment]
@jtheobaldhp  did you use version 0.10.8 or 0.10.8a? The former was missing a dependency that would explain the problem you experiences, while 0.10.8a fixes that.

I had forgotten to remove 0.10.8, apologies for that.

Jan Blom

**Comment by janblom** [comment]
The version with a missing dependency (0.10.8) has been removed from the release.  Version 0.10.8a should be used instead, and is included in the release.
